name: Test logtail-lambda-extension

on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test
    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
          cache-dependency-path: src/pnpm-lock.yaml
      - name: Install requirements
        run: pnpm --config.recursive-install=false install
      - name: Validate
        run: pnpm run validate
